/**
 * @fileoverview gRPC-Web generated client stub for greeter
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.6.1
// source: greeter.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.greeter = require('./greeter_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greeter.GreeterClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.greeter.GreeterPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.greeter.TranslationRequest,
 *   !proto.greeter.TranslationReply>}
 */
const methodDescriptor_Greeter_Greet = new grpc.web.MethodDescriptor(
  '/greeter.Greeter/Greet',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.greeter.TranslationRequest,
  proto.greeter.TranslationReply,
  /**
   * @param {!proto.greeter.TranslationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.greeter.TranslationReply.deserializeBinary
);


/**
 * @param {!proto.greeter.TranslationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greeter.TranslationReply>}
 *     The XHR Node Readable Stream
 */
proto.greeter.GreeterClient.prototype.greet =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greeter.Greeter/Greet',
      request,
      metadata || {},
      methodDescriptor_Greeter_Greet);
};


/**
 * @param {!proto.greeter.TranslationRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.greeter.TranslationReply>}
 *     The XHR Node Readable Stream
 */
proto.greeter.GreeterPromiseClient.prototype.greet =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/greeter.Greeter/Greet',
      request,
      metadata || {},
      methodDescriptor_Greeter_Greet);
};


module.exports = proto.greeter;

