apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
spec:
  selector:
    app: envoy-proxy
  ports:
  - name: http
    port: 10000
    targetPort: 10000
  - name: admin
    port: 9091
    targetPort: 9091
  type: NodePort
