apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
spec:
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
      - name: envoy-proxy
        image: k3d-myregistry.localhost:5001/lingua-greeter-server-envoy
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: admin
          containerPort: 9091
        - name: http
          containerPort: 10000
