FROM ubuntu

RUN apt-get update \
    && apt install -y curl ca-certificates curl \
    gnupg golang-go protobuf-compiler 

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28 \
    && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

ENV GOPATH=/root/go
ENV PATH="${PATH}:${GOPATH}/bin"

CMD [ "protoc" ]